<?php

declare(strict_types=1);
/** @var TubeArchivistButtonExtension $this */
$instance_url = FreshRSS_Context::userConf()->attributeString('tubearchivist_instance_url');
$api_token = FreshRSS_Context::userConf()->attributeString('tubearchivist_api_token');
$keyboard_shortcut = FreshRSS_Context::userConf()->attributeString('tubearchivist_shortcut');
$button_location = FreshRSS_Context::userConf()->attributeString('tubearchivist_button_location');
?>

<form action="<?= _url('extension', 'configure', 'e', urlencode($this->getName())); ?>" method="post">
  <input type="hidden" name="_csrf" value="<?= FreshRSS_Auth::csrfToken(); ?>" />
  <div class="form-group">
    <label class="group-name" for="tubearchivist_shortcut"><?= _t('ext.tubearchivistButton.configure.keyboard_shortcut'); ?></label>
    <div class="group-controls">
      <input type="text" name="tubearchivist_shortcut" id="tubearchivist_shortcut" maxlength="1" value="<?= $keyboard_shortcut; ?>">
    </div>

    <label class="group-name" for="tubearchivist_instance_url"><?= _t('ext.tubearchivistButton.configure.instance_url'); ?></label>
    <div class="group-controls">
      <input type="url" name="tubearchivist_instance_url" id="tubearchivist_instance_url" title="Please enter a valid URL starting with http:// or https://" value="<?= $instance_url; ?>" required>
    </div>
    <label class="group-name" for="tubearchivist_api_token"><?= _t('ext.tubearchivistButton.configure.api_token'); ?></label>
    <div class="group-controls">
      <input type="password" name="tubearchivist_api_token" id="tubearchivist_api_token" value="<?= $api_token; ?>" required>
    </div>

    <label class="group-name" for="tubearchivist_button_location"><?= _t('ext.tubearchivistButton.configure.button_location'); ?></label>
    <div class="group-controls">
      <select name="tubearchivist_button_location" id="tubearchivist_button_location">
        <option value="header_bottom" <?= ($button_location == "header_bottom") ? "selected" : "" ?>><?= _t('ext.tubearchivistButton.configure.button_location_header_bottom'); ?></option>
        <option value="header" <?= ($button_location == "header") ? "selected" : "" ?>><?= _t('ext.tubearchivistButton.configure.button_location_header'); ?></option>
        <option value="bottom" <?= ($button_location == "bottom") ? "selected" : "" ?>><?= _t('ext.tubearchivistButton.configure.button_location_bottom'); ?></option>
        <option value="hidden" <?= ($button_location == "hidden") ? "selected" : "" ?>><?= _t('ext.tubearchivistButton.configure.button_location_hidden'); ?></option>
      </select>
    </div>
  </div>

  <div class="form-group form-actions">
    <div class="group-controls">
      <button type="submit" class="btn btn-important"><?= _t('ext.tubearchivistButton.configure.save_changes'); ?></button>
    </div>
  </div>
</form>
